name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            Frontend/package-lock.json
            package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Frontend install
        working-directory: Frontend
        run: npm ci

      - name: Frontend typecheck
        working-directory: Frontend
        run: npm run type-check --if-present || npm run typecheck --if-present || echo "no typecheck script"

      - name: Frontend build
        working-directory: Frontend
        run: npm run build --if-present || echo "no build script"

      - name: Build WebSocketServer
        working-directory: WebSocketServer
        run: cargo build --locked --verbose

      - name: Build DatabaseProcessor
        working-directory: DatabaseProcessor
        run: cargo build --locked --verbose
